# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  matrix:
    linux:
      imageName: 'Ubuntu-16.04'
    windows:
      imageName: 'vs2017-win2016'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: ">=10.0"
- powershell: |
    ./build/environment-check.ps1
  displayName: "Build environment check"

- script: |
    cd scripts
    npm install
  displayName: "Installing node.js dependencies for scripts"

- powershell: |
    ./build/ci/rules-check.ps1
  displayName: "Checking repository rules"

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
